import { Tool, Workflow, Prompt, NewsArticle, Event } from '@/types'

export const mockTools: Tool[] = [
  {
    id: '1',
    name: 'Harvey AI',
    slug: 'harvey-ai',
    url: 'https://harvey.ai',
    tagline: 'KI-Assistent für komplexe Rechtsrecherche und Vertragsanalyse',
    description: 'Harvey nutzt speziell auf Rechtsfragen trainierte Sprachmodelle für Due Diligence, Vertragsanalyse und M&A-Transaktionen. Besonders stark bei komplexen grenzüberschreitenden Sachverhalten.',
    rechtsgebiet: ['M&A', 'Gesellschaftsrecht'],
    category: ['Recherche', 'Vertragsanalyse'],
    votes: 47,
    isNew: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    name: 'Taxdoo',
    slug: 'taxdoo',
    url: 'https://taxdoo.com',
    tagline: 'Automatisierte Steuerberechnung für digitale Transaktionen',
    description: 'Taxdoo automatisiert die steuerliche Behandlung komplexer Transaktionsstrukturen, insbesondere bei grenzüberschreitenden Sachverhalten und UStG-Anwendungsfragen.',
    rechtsgebiet: ['Steuerrecht'],
    category: ['Automatisierung', 'Steuer'],
    votes: 31,
    isNew: false,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    name: 'Luminance',
    slug: 'luminance',
    url: 'https://luminance.com',
    tagline: 'KI-gestützte Due Diligence und Vertragsanalyse auf Enterprise-Level',
    description: 'Luminance analysiert tausende Dokumente in Minuten und identifiziert kritische Klauseln, Abweichungen und Risiken in M&A-Prozessen. Breiter Einsatz in UK und zunehmend im DACH-Markt.',
    rechtsgebiet: ['M&A'],
    category: ['Due Diligence', 'Vertragsanalyse'],
    votes: 38,
    isNew: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    name: 'Legalese Decoder',
    slug: 'legalese-decoder',
    url: 'https://legalesedecoder.com',
    tagline: 'Komplexe Vertragsklauseln in Klartext übersetzen',
    description: 'Ideal für schnelle Erstbewertungen von Gesellschaftsverträgen und Investorenvereinbarungen. Unterstützt Deutsch und Englisch.',
    rechtsgebiet: ['Venture Capital', 'Gesellschaftsrecht'],
    category: ['Vertragsanalyse'],
    votes: 22,
    isNew: false,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    name: 'Doxly',
    slug: 'doxly',
    url: 'https://doxly.com',
    tagline: 'Transaktionsmanagement und Signing-Prozesse digitalisieren',
    description: 'Doxly optimiert den gesamten Closing-Prozess bei M&A-Transaktionen: Checklisten, Dokumentenmanagement und digitale Signatur in einem.',
    rechtsgebiet: ['M&A', 'Venture Capital'],
    category: ['Transaktionsmanagement'],
    votes: 19,
    isNew: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    name: 'Klarity',
    slug: 'klarity',
    url: 'https://klarity.ai',
    tagline: 'Automatische Extraktion von Vertragsdaten im großen Maßstab',
    description: 'Klarity extrahiert strukturierte Daten aus Verträgen und befüllt automatisch Datenräume. Besonders effizient bei Portfolioanalysen für VC-Investoren.',
    rechtsgebiet: ['Venture Capital', 'M&A'],
    category: ['Datenextraktion'],
    votes: 29,
    isNew: false,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockWorkflows: Workflow[] = [
  {
    id: '1',
    title: 'Due Diligence mit Claude: 5-Schritt-Workflow für M&A-Transaktionen',
    slug: 'due-diligence-claude-ma',
    rechtsgebiet: ['M&A'],
    readingTime: 15,
    excerpt: 'Wie du mit Claude strukturierte Legal DD in einem Bruchteil der Zeit durchführst — von der Dokumentensichtung bis zum Risikobericht.',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    title: 'Steuermemo automatisch generieren: Prompt-Kette für Assessoren',
    slug: 'steuermemo-prompt-kette',
    rechtsgebiet: ['Steuerrecht'],
    readingTime: 8,
    excerpt: 'Eine wiederverwendbare Prompt-Kette, die aus einem Sachverhalt ein strukturiertes Steuermemo nach Großkanzlei-Standard generiert.',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    title: 'Term Sheet Review mit KI: Was du prüfen solltest',
    slug: 'term-sheet-review-ki',
    rechtsgebiet: ['Venture Capital'],
    readingTime: 10,
    excerpt: 'Systematische KI-gestützte Analyse von VC Term Sheets: Anti-Dilution, Liquidationspräferenzen und Drag-along-Rechte auf einen Blick.',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    title: 'GmbH-Gründung automatisiert: Satzung und Gesellschaftsvertrag',
    slug: 'gmbh-gruendung-automatisiert',
    rechtsgebiet: ['Gesellschaftsrecht'],
    readingTime: 12,
    excerpt: 'Von der Mandatsannahme bis zur notarfähigen Satzung: Wie du den Standardfall einer GmbH-Gründung mit KI deutlich beschleunigst.',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockPrompts: Prompt[] = [
  {
    id: '1',
    title: 'GmbH-Anteilsübertragung: § 17 EStG Prüfungsschema',
    slug: 'gmbh-anteilsuebertragung-17-estg',
    promptText: `Du bist ein erfahrener Steuerberater. Prüfe den folgenden Sachverhalt auf seine steuerlichen Folgen nach § 17 EStG. Gehe dabei strukturiert vor: (1) Tatbestandsvoraussetzungen prüfen, (2) Veräußerungsgewinn berechnen, (3) Teileinkünfteverfahren anwenden, (4) Gestaltungshinweise geben. Sachverhalt: [SACHVERHALT EINFÜGEN]`,
    useCase: 'Steuerliche Prüfung bei GmbH-Anteilsveräußerungen',
    rechtsgebiet: ['Steuerrecht', 'M&A'],
    exampleOutput: 'Strukturiertes Steuermemo mit Prüfungsschema, Berechnung und Gestaltungsempfehlungen',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Due Diligence Red Flag Scanner',
    slug: 'due-diligence-red-flag-scanner',
    promptText: `Analysiere den folgenden Vertragstext auf kritische Klauseln und Red Flags aus M&A-Perspektive. Kategorisiere deine Findings nach: (1) Deal Breaker, (2) Nachverhandlungsbedarf, (3) Standard-Abweichungen, (4) Positiv-Klauseln. Gib für jeden Fund eine Risikoeinschätzung (hoch/mittel/niedrig). Vertragstext: [TEXT EINFÜGEN]`,
    useCase: 'Schnelle Vertragsanalyse im M&A-Prozess',
    rechtsgebiet: ['M&A'],
    exampleOutput: 'Strukturierte Tabelle mit Risk Flags, Kategorisierung und Handlungsempfehlungen',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    title: 'Venture Capital Term Sheet Decoder',
    slug: 'vc-term-sheet-decoder',
    promptText: `Du bist VC-erfahrener Anwalt. Erkläre die folgenden Term-Sheet-Klauseln auf Deutsch in einfacher Sprache: Was bedeuten sie konkret? Welche wirtschaftlichen Auswirkungen haben sie für Gründer vs. Investor? Welche Verhandlungsposition ist marktüblich? Klausel: [KLAUSEL EINFÜGEN]`,
    useCase: 'Term Sheet Verhandlung und Mandantenberatung',
    rechtsgebiet: ['Venture Capital'],
    exampleOutput: 'Klare Erklärung, wirtschaftliche Implikationen, Marktstandard und Verhandlungsspielraum',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    title: 'Gesellschafterbeschluss Prüfung',
    slug: 'gesellschafterbeschluss-pruefung',
    promptText: `Prüfe den folgenden Gesellschafterbeschluss auf formelle und materielle Wirksamkeit nach GmbHG/AktG. Gehe ein auf: (1) Einberufung und Frist, (2) Beschlussfähigkeit, (3) erforderliche Mehrheiten, (4) Beurkundungspflichten, (5) Anfechtungsrisiken. Beschluss: [BESCHLUSS EINFÜGEN]`,
    useCase: 'Wirksamkeitsprüfung von Gesellschafterbeschlüssen',
    rechtsgebiet: ['Gesellschaftsrecht'],
    exampleOutput: 'Strukturiertes Rechtsgutachten mit Prüfungspunkten und Handlungsempfehlungen',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    title: 'UmwStG Aktennotiz Generator',
    slug: 'umwstg-aktennotiz-generator',
    promptText: `Erstelle eine Aktennotiz auf Partnerniveau zur steuerlichen Behandlung der folgenden Umstrukturierung unter dem UmwStG. Prüfe: anwendbare UmwStG-Vorschriften, Buchwertansatz vs. gemeiner Wert, Behaltefristen, GrESt-Implikationen. Sachverhalt: [SACHVERHALT]`,
    useCase: 'UmwStG-Beratung und Aktennotizen auf Partnerniveau',
    rechtsgebiet: ['Steuerrecht', 'M&A'],
    exampleOutput: 'Strukturierte Aktennotiz mit Tatbestand, Rechtslage, Ergebnis und Empfehlung',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    title: 'NDA Schnellcheck',
    slug: 'nda-schnellcheck',
    promptText: `Analysiere das folgende NDA auf die 5 wichtigsten Verhandlungspunkte aus Mandantenperspektive: (1) Schutzgegenstand, (2) Laufzeit, (3) Ausnahmen, (4) Vertragsstrafe, (5) Rückgabe/Vernichtung. Gib direkte Handlungsempfehlungen. NDA: [TEXT]`,
    useCase: 'Schnellbewertung von NDAs vor Verhandlung',
    rechtsgebiet: ['M&A', 'Gesellschaftsrecht'],
    exampleOutput: 'Stichpunktartige Analyse mit konkreten Änderungsvorschlägen',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockNews: NewsArticle[] = [
  {
    id: '1',
    title: 'BFH: Neue Grundsätze zur Besteuerung von Carried Interest bei PE-Fonds',
    slug: 'bfh-carried-interest-pe-fonds',
    summary: 'Der BFH hat in einem Grundsatzurteil die steuerliche Einordnung von Carried Interest bei Private-Equity-Fonds als Einkünfte aus Kapitalvermögen präzisiert.',
    sourceUrl: '#',
    sourceName: 'BFH',
    category: 'Steuerrecht',
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    aiGenerated: true,
  },
  {
    id: '2',
    title: 'BGH stärkt Minderheitsgesellschafter: Neue Anforderungen an Squeeze-out',
    slug: 'bgh-squeeze-out-minderheitsschutz',
    summary: 'Der BGH verschärft die Anforderungen an die Angemessenheit der Abfindung beim aktienrechtlichen Squeeze-out und verlangt eine umfassendere Unternehmensbewertung.',
    sourceUrl: '#',
    sourceName: 'BGH',
    category: 'Gesellschaftsrecht',
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    aiGenerated: true,
  },
  {
    id: '3',
    title: 'Harvey AI erhält 300 Mio. Dollar Series D — europäische Expansion geplant',
    slug: 'harvey-ai-series-d-europa',
    summary: 'Das Legal-AI-Startup Harvey hat eine Series-D-Finanzierungsrunde abgeschlossen und kündigt die Expansion in den deutschsprachigen Markt an.',
    sourceUrl: '#',
    sourceName: 'JUVE',
    category: 'Legal Tech',
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    aiGenerated: true,
  },
  {
    id: '4',
    title: 'BMF-Schreiben: Klarstellungen zur Besteuerung von Token-basierten Assets',
    slug: 'bmf-token-assets-besteuerung',
    summary: 'Das BMF hat ein lang erwartetes Schreiben zur ertragsteuerlichen Behandlung von Krypto-Assets und tokenisierten Wertpapieren veröffentlicht.',
    sourceUrl: '#',
    sourceName: 'BMF',
    category: 'Steuerrecht',
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    aiGenerated: true,
  },
  {
    id: '5',
    title: 'Freshfields und Linklaters testen KI-gestützte Due Diligence im DACH-Markt',
    slug: 'freshfields-linklaters-ki-due-diligence',
    summary: 'Zwei der größten internationalen Wirtschaftskanzleien pilotieren KI-basierte Due-Diligence-Tools für deutsche M&A-Mandate.',
    sourceUrl: '#',
    sourceName: 'LTO',
    category: 'Legal Tech',
    publishedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    aiGenerated: false,
  },
  {
    id: '6',
    title: 'EU AI Act: Erste Compliance-Anforderungen für Legal-Tech-Anbieter in Kraft',
    slug: 'eu-ai-act-legal-tech-compliance',
    summary: 'Mit dem schrittweisen Inkrafttreten des AI Acts müssen Legal-Tech-Anbieter nun konkrete Transparenz- und Dokumentationspflichten erfüllen.',
    sourceUrl: '#',
    sourceName: 'LTO',
    category: 'Regulierung',
    publishedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    aiGenerated: false,
  },
]

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'BFH-Verhandlung: Umwandlungssteuerrecht bei grenzüberschreitenden Verschmelzungen',
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    type: 'BFH',
    url: '#',
    description: 'Az. I R 22/24',
  },
  {
    id: '2',
    title: 'Referentenentwurf: Modernisierung des GmbH-Rechts',
    date: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    type: 'Gesetz',
    url: '#',
    description: 'Anhörungsfrist endet',
  },
  {
    id: '3',
    title: 'JUVE M&A Summit 2025 — Frankfurt',
    date: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    type: 'Konferenz',
    url: '#',
    description: 'Transaktionen, KI-Tools, Legal Tech',
  },
  {
    id: '4',
    title: 'BGH-Urteil: Haftung des Aufsichtsrats bei KI-gestützten Entscheidungen',
    date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    type: 'BGH',
    url: '#',
    description: 'Az. II ZR 14/24 — Erstinstanz',
  },
]
